spring:
  application:
    name: jvm-optimize

  datasource:
      url: jdbc:mysql://192.168.88.130:3306/test?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: tour
      password: tour
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      maxActive: 100
      testOnBorrow: true
      validationQuery: SELECT 1

mybatis-plus:
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mama.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: false
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: kzj_gd_
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    db-type: mysql
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    #jdbc-type-for-null: 'null'

  jackson:
    dateFormat: yyyy-MM-dd'T'hh:mm:ss

server:
  port: 8701


#  ribbon:
#    ReadTimeout: 65000
#    ConnectTimeout: 65000

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
       defaultZone: http://localhost:8700/eureka/
    registry-fetch-interval-seconds: 10


## 配置hystrix
#feign:
#  hystrix:
#    enabled: true
#
#hystrix:
#  threadpool:
#    default:
#      coreSize: 10  #线程池核心线程数
#  command:
#    #IService#hello(): 设置某一个接口 default: 设置全部接口
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 65000 #超时时间
#      circuitBreaker:
#        requestVolumeThreshold: 20  #当在配置时间窗口内达到此数量后，进行短路。默认20个
#        sleepWindowInMilliseconds: 5  #短路多久以后开始尝试是否恢复，默认5s
#        errorThresholdPercentage: 50%  #出错百分比阈值，当达到此阈值后，开始短路。默认50%